# Site settings
title: "Motivated Text"
email: jacob@jacobtomlinson.co.uk
description: "A dark blog theme for Jekyll."
baseurl: ""
url: ""
title_description: "Adventures in Text animation on iOS by Paul Warren"
title_image: "MT.png"
google_analytics: ""
disqus_account: 
github_repository: https://github.com/pawpoise/github.io
addthis_id:
post_limit: 5

# Social usernames/URLs
twitter_username: pawpoise
github_username:  pawpoise
instagram_username: 
reddit_username: 
linkedin_link: https://www.linkedin.com/in/paul-warren-b109b230/

# Footer
footer_left: "Written by <a href=\"https://twitter.com/pawpoise\">Paul Warren</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/pawpoise\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
